"""
Django settings for UniDjango project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import datetime
import os   # 构建镜像用

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-_m2_u3wj481scr)xes3z-2peg!-eg+-*g=@e=130bh%ta(b757'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # 'django.contrib.admin', 
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'user.apps.UserConfig',  #用户模块配置
    'menu.apps.MenuConfig',  #菜单模块配置
    'role.apps.RoleConfig',  #角色模块配置
    'department.apps.DepartmentConfig',  #部门模块配置
    'auto.apps.AutoConfig',  #自动代码测试模块配置
    'log.apps.LogConfig',  #日志监控模块配置
    'rest_framework',  # Django REST framework
    'rest_framework_jwt',  # JWT authentication for Django REST framework
    'corsheaders',  #  跨域请求处理
    'django_filters',  # Django过滤器支持
    'drf_yasg',  # Swagger文档生成
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # 跨域中间件,必须放在第一位
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',  #去掉csrf
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'log.middleware.RequestLogMiddleware', # 请求日志中间件
    'user.middleware.JwtAuthenticationMiddleware',  # JWT_TOKEN 认证中间件
]


# 跨域相关配置
CORS_ORIGIN_ALLOW_ALL = True  # 允许所有域名跨域请求 
CORS_ALLOW_CREDENTIALS = True  # 允许携带cookie等凭证信息
CORS_ALLOW_METHODS = [
    'GET', 'POST', 'PUT', 'DELETE', 'PATCH',  # 允许的HTTP方法
]

# CSRF 配置
# CSRF_TRUSTED_ORIGINS = [
#     'http://localhost:9528',
#     'http://127.0.0.1:9528',
# ]



ROOT_URLCONF = 'UniDjango.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'UniDjango.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'unidjango',     # 数据库名
        'USER': 'root',         # MySQL 用户名
        'PASSWORD': 'Pm6yj3333',     # MySQL 密码
        # 'HOST': 'localhost',             # 数据库主机（或 IP）
        'HOST': os.environ.get('DB_HOST', 'localhost'), 
        'PORT': '3306',                  # MySQL 端口（默认 3306）
        'OPTIONS': {
            'charset': 'utf8mb4',        # 支持 Emoji 和特殊字符
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# JWT 配置：访问 token 7 天过期，可刷新期 30 天
# JWT认证配置
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=30),
}

# Django REST Framework 分页配置
REST_FRAMEWORK = {
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',  # 启用django-filter过滤后端
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'MAX_PAGE_SIZE': 100,  # 最大每页记录数
    'PAGE_SIZE': 10,  # 默认每页显示10条记录
    'PAGE_SIZE_QUERY_PARAM': 'page_size',  # 允许前端通过page_size参数自定义每页大小
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'user.authentication.PreAuthenticatedAuthentication', # 使用中间件认证的结果
    ], 
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny', # 默认允许所有，权限由中间件控制或视图单独控制
    ],
}

# 媒体文件（上传/存放的图片等）配置
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# 关闭自动追加斜杠，避免无斜杠的 PUT/PATCH/POST 被强制重定向到带斜杠 URL
APPEND_SLASH = False