# Generated by Django 5.2.4 on 2025-09-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sysauto',
            old_name='name',
            new_name='dep_name',
        ),
    ]
